site_name: GenIR Notes
site_url: https://genir-notes.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
plugins:
  - search

extra:
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/GenIR-notes/genir-notes
  #     name: "Star us on GitHub!"
  #   - icon: fontawesome/solid/eye
  #     link: https://github.com/GenIR-notes/genir-notes/watchers
  #     name: "Watch updates"


nav:
  - Home: index.md
  - Get Started: resources.md
  - Document Retrieval:
      - Roadmap: document_retrieval/roadmap.md
      - Papers: document_retrieval/papers.md
  - Recommendation:
      - Roadmap: recommendation/roadmap.md
      - Papers: recommendation/papers.md
  - Multimodal Retrieval & Recommendation:
      - Roadmap: multimodal/roadmap.md
      - Papers: multimodal/papers.md


