site_name: GenIR Notes
site_url: https://genir-notes.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
plugins:
  - search
  - include-markdown:
      recursive: false

# extra:
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/GenIR-notes/genir-notes
  #     name: "Star us on GitHub!"
  #   - icon: fontawesome/solid/eye
  #     link: https://github.com/GenIR-notes/genir-notes/watchers
  #     name: "Watch updates"


nav:
  - Home: index.md
  - Get Started: resources.md
  - Document Retrieval:
      - Roadmap: document_retrieval/roadmap.md
      - Papers: document_retrieval/papers.md
  - Recommendation:
      - Roadmap: recommendation/roadmap.md
      - Papers: recommendation/papers.md
  - Multimodal Retrieval & Recommendation:
      - Roadmap: multimodal/roadmap.md
      - Papers: multimodal/papers.md
  - Recent Updates: recent.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - admonition
  - attr_list
  - md_in_html

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/filter-tags.js
  - js/recent.js

extra_css:
  - css/extra.css
